name: firstapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  bloc: ^7.0.0
  rxdart: ^0.27.1
  dio: ^4.0.0
  eva_icons_flutter: ^3.0.0
  carousel_slider: ^4.0.0
  timeago: ^3.1.0
  flutter_html: ^2.1.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
assets:
  assets:
    - img/placeholder.jpg
    - logos/abc-news.png
    - logos/al-jazeera-english.png
    - logos/ars-technica.png
    - logos/associated-press.png
    - logos/axios.png
    - logos/bbc-news.png
    - logos/bbc-sport.png
    - logos/bleacher-report.png
    - logos/bloomberg.png
    - logos/business-insider.png
    - logos/buzzfeed.png
    - logos/cbc-news.png
    - logos/cbs-news.png
    - logos/cnn.png
    - logos/espn.png
    - logos/financial-post.png
    - logos/fortune.png
    - logos/fox-news.png
    - logos/fox-sports.png
    - logos/google-news.png
    - logos/hacker-news.png
    - logos/ign.png
    - logos/independent.png
    - logos/mashable.png
    - logos/msnbc.png
    - logos/mtv-news.png
    - logos/national-geographic.png
    - logos/news24.png
    - logos/politico.png
    - logos/recode.png
    - logos/reuters.png
    - logos/rte.png
    - logos/techcrunch.png
    - logos/techradar.png
    - logos/the-hill.png
    - logos/the-huffington-post.png
    - logos/the-next-web.png
    - logos/the-wall-street-journal.png
    - logos/the-washington-post.png
    - logos/time.png
    - logos/wired.png
    - logos/breitbart-news.png
    - logos/crypto-coins-news.png
    - logos/engadget.png
    - logos/entertainment-weekly.png
    - logos/espn-cric-info.png
    - logos/medical-news-today.png
    - logos/national-review.png
    - logos/nbc-news.png
    - logos/new-scientist.png
    - logos/newsweek.png
    - logos/next-big-future.png
    - logos/nfl-news.png
    - logos/nhl-news.png
    - logos/polygon.png
    - logos/reddit-r-all.png
    - logos/new-york-magazine.png
    - logos/the-american-conservative.png
    - logos/the-verge.png
    - logos/the-washington-times.png
    - logos/usa-today.png
    - logos/vice-news.png
    - logos/logo_placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
